# Generated by Django 4.2.1 on 2023-07-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draburst_forum', '0003_comment_remove_product_category_delete_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publ_data',
            new_name='publiched_date',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
